'''
NumPy (Numerical Python): an open source Python library.
The fundamental package for scientific computing in Python.
The NumPy API is used extensively in Pandas, SciPy, 
Matplotlib, scikit-learn, scikit-image and most other 
data science and scientific Python packages.

It provides ndarray, a homogeneous n-dimensional array object, 
with methods to efficiently operate on it.
'''

In [1]:
#To access NumPy and its functions import it in your Python code

import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
'''
Most NumPy arrays have some restrictions. For instance:
All elements of the array must be of the same type of data.
Once created, the total size of the array can’t change.
The shape must be “rectangular”, not “jagged”; e.g., each 
row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics
to make the array faster, more memory efficient, and more convenient
to use than less restrictive data structures.
'''

In [3]:
print(f"Type: {type(a)}")

Type: <class 'numpy.ndarray'>


In [4]:
# ndim: no. of axes (dimension)

print(f"Number of axes: {a.ndim}")

Number of axes: 2


In [5]:
# shape: tuple of non-negative integers 
# that specify the number of elements along each dimension

print(f"Dimensions: {a.shape}")

Dimensions: (2, 3)


In [6]:
# size: total no. of elements

print(f"No. of elements: {a.size}")

No. of elements: 6


In [7]:
# dtype: type of elements

print(f"Type of elements: {a.dtype}")

Type of elements: int32


In [8]:
# itemsize: the size in bytes of each element of the array

print(f"Size (in bytes) of each element: {a.itemsize}")

Size (in bytes) of each element: 4


In [9]:
# nbytes: number of bytes used by data portion of the array

print(f"Size (in bytes) of the array: {a.nbytes}")

Size (in bytes) of the array: 24


In [10]:
# data: buffer containing the elements of the array

print(f"Buffer: {a.data}")

Buffer: <memory at 0x0000014B0A0F9D80>


In [11]:
# strides : how many bytes to skip in memory to move to 
# the next position along a certain axis

print(a.strides)

(12, 4)


In [12]:
# Array Creation
# np.array(), np.zeros(), np.ones(), np.empty(), 
# np.arange(), np.linspace(), dtype

# np.array : from list or tuples

np.array([1, 2, 3])

array([1, 2, 3])

In [13]:
# zeros: creates an array full of zeros
# zeros(shape, dtype='float64')
# shape is a number or sequence specifying
# dimensions of the array

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros((2, 3), dtype = 'int16')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [15]:
# ones: creates an array full of ones
# ones(shape, dtype='float64')

np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# empty: creates an array whose 
# initial content is random and 
# depends on the state of the memory

np.empty((3,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.29061074e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 0.00000000e+000]])

In [17]:
np.full((3,2), 55.55)

array([[55.55, 55.55],
       [55.55, 55.55],
       [55.55, 55.55]])

In [18]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# arange: Nearly analogous to the Python built-in range, 
# but returns an array

np.arange(1, 9, 2)

array([1, 3, 5, 7])

In [20]:
# linspace: evenly spaced elements in
# a specified interval
# i.e. between (and including) start and stop 

np.linspace(-2, 4, 9)

array([-2.  , -1.25, -0.5 ,  0.25,  1.  ,  1.75,  2.5 ,  3.25,  4.  ])

In [21]:
# reshape
# affect the array structure, not the data

a = np.arange(12)
b = a.reshape(4, 3)     # 2d array
print(b)
print(a.strides, b.strides)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4,) (12, 4)


In [22]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [23]:
# Basic Operations
# Arithmetic operators on arrays apply elementwise. 
# A new array is created and filled with the result.

In [24]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
print(a)
print(b)
print(c)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]


In [25]:
b ** 2

array([0, 1, 4, 9])

In [26]:
a < 35

array([ True,  True, False, False])

In [27]:
5 * a

array([100, 150, 200, 250])

In [28]:
# matrix product can be performed using 
# the @ operator (in python >=3.5) or the dot function or method

A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [29]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [30]:
A.dot(B)  # matrix product

array([[5, 4],
       [3, 4]])

In [31]:
# Indexing and Slicing
# 1-d arrays can be indexed and sliced much like lists and other Python sequences

a = np.arange(10)**3

print(f"a: {a}\n")  # [  0,   1,   8,  27,  64, 125, 216, 343, 512, 729]

print(f"a[2]: {a[2]}\n")    # 8

print(f"a[2:5]: {a[2:5]}\n")  # [ 8, 27, 64]

# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
print(f"{a}\n")     # [1000, 1, 1000, 27, 1000, 125, 216, 343, 512, 729]

print("Reversed:", a[::-1])  # reversed a
            # [ 729, 512, 343, 216, 125, 1000, 27, 1000, 1, 1000]

a: [  0   1   8  27  64 125 216 343 512 729]

a[2]: 8

a[2:5]: [ 8 27 64]

[1000    1 1000   27 1000  125  216  343  512  729]

Reversed: [ 729  512  343  216  125 1000   27 1000    1 1000]


In [32]:
# Multidimensional arrays can have one index per axis. 
# These indices are given in a tuple separated by commas.

def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)

print(f"b:\n{b}")
                # [[ 0,  1,  2,  3],
                #  [10, 11, 12, 13],
                #  [20, 21, 22, 23],
                #  [30, 31, 32, 33],
                #  [40, 41, 42, 43]]

print(f"\nb[2,3]:{b[2, 3]}\n")   # 23

print(f"b[0:5,1]:{b[0:5, 1]}\n")  # each row in the second column of b
                                # [ 1, 11, 21, 31, 41]
# b[:, 1]    # equivalent to the previous example

print(f"b[1:3,:]:\n{b[1:3,:]}\n")  # each column in the second and third row of b
                                # [[10, 11, 12, 13],
                                #  [20, 21, 22, 23]]
        
# When fewer indices are provided than the number of axes, 
# the missing indices are considered complete slices
print(f"\nb[-1]: {b[-1]}")   # the last row. Equivalent to b[-1, :]
                          # [40, 41, 42, 43]
    
# The expression within brackets in b[i] is treated as 
# an i followed by as many instances of : as needed to 
# represent the remaining axes. 

b:
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

b[2,3]:23

b[0:5,1]:[ 1 11 21 31 41]

b[1:3,:]:
[[10 11 12 13]
 [20 21 22 23]]


b[-1]: [40 41 42 43]


In [ ]:
''' Array copy and view

The copy owns the data and any changes made to the copy 
will not affect original array, and any changes made 
to the original array will not affect the copy.

The view does not own the data and any changes made 
to the view will affect the original array, 
and any changes made to the original array will affect the view.

Every NumPy array has the attribute base that 
returns None if the array owns the data.
Otherwise, the base attribute refers to the original object.

'''

In [33]:
# Copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

arr[0] = 11
x[4] = 55

print("Array: ", arr)  # changes made to the copy NOT affect original array
print("Copy: ", x) # changes made to the original array NOT affect the copy

print(x.base)

Array:  [11  2  3  4  5]
Copy:  [ 1  2  3  4 55]
None


In [34]:
# View

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

arr[0] = 11
x[4] = 55

print("Array: ", arr)  # changes made to the copy affect original array
print("View: ", x) # changes made to the original array affect the copy

print(x.base)

Array:  [11  2  3  4 55]
View:  [11  2  3  4 55]
[11  2  3  4 55]


In [ ]:
'''Slice indexing of a list copies the elements into a new list, 
but slicing an array returns a view: an object that refers to 
the data in the original array. The original array can be mutated 
using the view.
'''

In [35]:
# Fancy indexing - two types (i) integer and (ii) boolean
# Fancy indexing returns a copy of the data
# whereas basic slicing returns a view

In [36]:
a = np.arange(0, 100, 10)
print(a)

indices = np.array([2, 5, -3])
b = a[indices]
print(b)

[ 0 10 20 30 40 50 60 70 80 90]
[20 50 70]


In [37]:
a[indices] = 999
print(a)

[  0  10 999  30  40 999  60 999  80  90]


In [38]:
mask = np.array([0, 0, 1, 0, 0, 1, 0, 1, 0, 0], dtype=bool)
print(mask)

b = a[mask]
print(b)

[False False  True False False  True False  True False False]
[999 999 999]


In [39]:
a = np.arange(24).reshape(4,6)
print(a)

print(a[[0, 2, 3],[2, 4, 3]]) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 2 16 21]


In [40]:
a[1:, [0,2,5]]

array([[ 6,  8, 11],
       [12, 14, 17],
       [18, 20, 23]])

In [41]:
mask = np.array([1, 0, 1, 1], dtype=bool)
a[mask,3]

array([ 3, 15, 21])

In [42]:
mask = a > 15
a[mask]

array([16, 17, 18, 19, 20, 21, 22, 23])